local config = require("image-insert.config")

describe("config", function()
  it("should have default options", function()
    config.setup({})
    assert.are.equal("img", config.get_opt("dir_path"))
    assert.are.equal("png", config.get_opt("extension"))
  end)

  it("should merge options", function()
    config.setup({ dir_path = "assets" })
    assert.are.equal("assets", config.get_opt("dir_path"))
    assert.are.equal("png", config.get_opt("extension"))
  end)
end)
